# 1. NumPy - Arrays 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Using NumPy

In [3]:
import numpy as np # alias


# Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d


## Creating NumPy Arrays

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

In [9]:
list(range(0,10)) # python method

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10, 40, 2) # (start, stop, step)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

### zeros and ones

Generate arrays of zeros or ones

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(0, 1, 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

## eye

Creates an identity matrix

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [29]:
np.random.rand(5)

array([0.3423999 , 0.9517386 , 0.08262931, 0.52443969, 0.74996845])

In [33]:
np.random.rand(5,5)

array([[0.39893123, 0.28719281, 0.27887029, 0.08967886, 0.47823746],
       [0.49127372, 0.73142006, 0.4347659 , 0.26061704, 0.65506302],
       [0.92081862, 0.33908194, 0.90154571, 0.45520763, 0.21913023],
       [0.86806054, 0.7765257 , 0.09164455, 0.02993188, 0.590114  ],
       [0.92550469, 0.35417577, 0.34437316, 0.24397658, 0.32930773]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [38]:
np.random.randn(5)

array([ 0.00355991, -0.40699896, -0.43316255, -1.13959035,  1.16215189])

In [41]:
np.random.randn(5,5)

array([[ 2.15749774,  0.27917873,  0.54264308, -0.96496019, -1.11010099],
       [-0.43635   ,  0.06958992,  2.38350974, -1.07271391, -0.22028079],
       [-1.25785125, -2.06482832, -0.53590051,  0.4442135 , -0.3222157 ],
       [-0.53176874,  0.29466421, -1.49037994, -2.29015772,  0.77183219],
       [-1.27366133, -0.644927  , -0.76641298,  0.09081173,  0.0104811 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [51]:
np.random.randint(0, 100)

20

In [49]:
np.random.randint(1, 100, 10)

array([79, 80, 50, 30, 76,  7, 16, 56,  6, 92])

## Reshape
Returns an array containing the same data with a new shape.

In [52]:
arr = [1,3,5,6,4,5,7,7,9]
arr = np.array(arr)

In [53]:
arr

array([1, 3, 5, 6, 4, 5, 7, 7, 9])

In [54]:
arr = arr.reshape(3,3)

In [55]:
arr

array([[1, 3, 5],
       [6, 4, 5],
       [7, 7, 9]])

In [59]:
arr1 = [1,3,5,6]
arr1 = np.array(arr1)

In [68]:
arr1 = arr1.reshape(2,2)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [63]:
arr

array([[1, 3, 5],
       [6, 4, 5],
       [7, 7, 9]])

In [64]:
arr.max()

9

In [65]:
arr.min()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [71]:
# Vector
arr.shape

(3, 3)

In [72]:
arr = [1,3,5,6,4,5,7,7,2,1,3,5,6,4,5,7,7,2,1,3,5,6,4,5,7]
arr = np.array(arr)

In [73]:
arr

array([1, 3, 5, 6, 4, 5, 7, 7, 2, 1, 3, 5, 6, 4, 5, 7, 7, 2, 1, 3, 5, 6,
       4, 5, 7])

In [74]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[1, 3, 5, 6, 4, 5, 7, 7, 2, 1, 3, 5, 6, 4, 5, 7, 7, 2, 1, 3, 5, 6,
        4, 5, 7]])

In [75]:
arr.reshape(1,25).shape

(1, 25)

In [76]:
arr.reshape(25,1)

array([[1],
       [3],
       [5],
       [6],
       [4],
       [5],
       [7],
       [7],
       [2],
       [1],
       [3],
       [5],
       [6],
       [4],
       [5],
       [7],
       [7],
       [2],
       [1],
       [3],
       [5],
       [6],
       [4],
       [5],
       [7]])

In [77]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [78]:
arr.dtype

dtype('int64')

In [79]:
arr1 = [1,3,5,6,4,5,7,7,2,1,"abc"]
arr1 = np.array(arr1)

In [80]:
arr1.dtype

dtype('<U21')