# 2. NumPy Indexing and Selection

In [1]:
import numpy as np

In [4]:
arr = np.arange(0, 21, 2)

In [5]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## Bracket Indexing and Selection

In [7]:
arr[2]

4

In [9]:
arr[2:]

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
arr[6:9]

array([12, 14, 16])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [11]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
arr[0:5] = 404

In [13]:
arr

array([404, 404, 404, 404, 404,  10,  12,  14,  16,  18,  20])

In [14]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20])

In [21]:
arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slicing

In [16]:
slice_of_arr = arr[0:6]

slice_of_arr

array([1, 2, 3, 4, 5, 6])

In [17]:
slice_of_arr[:] = 10

In [18]:
slice_of_arr

array([10, 10, 10, 10, 10, 10])

In [19]:
arr

array([10, 10, 10, 10, 10, 10,  7,  8,  9, 10])

In [22]:
arr_copy = arr.copy()

arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**.

In [23]:
arr_2d = np.array(([5,2],[20,12]))

arr_2d

array([[ 5,  2],
       [20, 12]])

In [24]:
arr_2d[1]

array([20, 12])

In [26]:
arr_2d[1][1]

12

In [27]:
arr_2d[1, 1]

12

In [29]:
arr_2d[0,0]

5

In [30]:
arr_2d

array([[ 5,  2],
       [20, 12]])

## Selection - Comparsion Operators

In [31]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [33]:
bool_arr = arr <= 4

In [34]:
bool_arr

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [35]:
arr[bool_arr]

array([1, 2, 3, 4])

In [39]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
x = 6
arr[arr>x]

array([ 7,  8,  9, 10])