# 3. NumPy Operations

## Arithmetic

In [1]:
import numpy as np
arr = np.arange(0,10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1 = [[0, 1, 2], [3, 4, 5], [1, 5, 9]]
arr2 = [[1, 2, 9], [9, 1, 3], [1, 8, 9]]

In [9]:
arr1

[[0, 1, 2], [3, 4, 5], [1, 5, 9]]

In [10]:
arr1 = np.array(arr1)
arr2 = np.array(arr2)

In [11]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [1, 5, 9]])

In [12]:
arr2

array([[1, 2, 9],
       [9, 1, 3],
       [1, 8, 9]])

In [13]:
arr1 * arr2

array([[ 0,  2, 18],
       [27,  4, 15],
       [ 1, 40, 81]])

In [14]:
arr1 + arr2

array([[ 1,  3, 11],
       [12,  5,  8],
       [ 2, 13, 18]])

In [15]:
arr1 - arr2

array([[-1, -1, -7],
       [-6,  3,  2],
       [ 0, -3,  0]])

In [16]:
arr1 / arr2

array([[0.        , 0.5       , 0.22222222],
       [0.33333333, 4.        , 1.66666667],
       [1.        , 0.625     , 1.        ]])

In [17]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/var/folders/zd/4j5y4mxs0qddsylq3q_l8skw0000gn/T/ipykernel_38246/2878212635.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [20]:
# Also warning, but not an error instead infinity
1/0

ZeroDivisionError: division by zero

In [21]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [24]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [25]:
np.max(arr) #same as arr.max()

9

In [26]:
arr.max()

9

In [27]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [28]:
np.log(arr)

/var/folders/zd/4j5y4mxs0qddsylq3q_l8skw0000gn/T/ipykernel_38246/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])